baseURL = "https://antmoe.gitee.io/"
languageCode = "en-us"
title = "小康的学习博客"
theme = "LeaveIt"
paginate = 12
enableEmoji = true
enableRobotsTXT = true
googleAnalytics = ""

preserveTaxonomyNames = true

[blackfriday]
  hrefTargetBlank = true
  nofollowLinks = true
  noreferrerLinks = true

[Permalinks]
 posts = "/:year/:filename/"

[menu]
  [[menu.main]]
    name = "Blog"
    url = "/posts/"
    weight = 1

  [[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 2

  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 3

  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 4

[params]
    since = 2020
    author = "Dreamy.TZK"                           # Author's name
    avatar = "https://cdn.jsdelivr.net/gh/sviptzk/HexoStaticFile@latest/avatar.jpg"           # Author's avatar
    subtitle = "When your talent can't support your ambition ,you should study calmly"         # Subtitle
    cdn_url = ""           # Base CDN URL
    home_mode = "" # post or other

    google_verification = ""
   
    description = "一个收藏回忆与分享技术的地方！" # site description
    keywords = "小康博客" # site keywords

    beian = ""
    baiduAnalytics = ""

    license= '本文采用<a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/" target="_blank">知识共享署名-非商业性使用 4.0 国际许可协议</a>进行许可'

[params.social]
    GitHub = "sviptzk"
    #Twitter = "xxoo"
    Email   = "sviptzk@163.com"
    #Instagram = "xxoo"
    #Wechat = "/images/me/wechat.png"  # Wechat QRcode image
    #Facebook = "xxoo"
    #Telegram = "xxoo"
    #Dribbble = "xxoo"
    #Medium = "xxoo"

